# Generated by Django 4.0.2 on 2022-03-20 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpiModel',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.IntegerField()),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macbeth.epimodel')),
            ],
        ),
    ]
